// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aspxfistqymrylfagnhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzcHhmaXN0cXltcnlsZmFnbmh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzc5OTEsImV4cCI6MjA2Mzc1Mzk5MX0._VLTBm4aqMRleSFROVmPIZObCIhZUCd83oTLQC4ei2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);